# Generated by Django 4.0.4 on 2022-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TN', 'Танк'), ('HL', 'Хил'), ('DD', 'ДД'), ('VN', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('BS', 'Кузнец'), ('TN', 'Кожевенник'), ('PM', 'Зельевар'), ('SM', 'Мастер заклинаний'), ('OR', 'Другое')], default='OR', max_length=2),
        ),
    ]
